import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/Navbar"

const poppins = Poppins({ subsets: ["latin"], weight: "600" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode
  modal: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="h-screen overflow-y-scroll">
          <Navbar />
          {children}
        </div>
        {modal}
      </body>
    </html>
  )
}
